package com.vocabdaily.widget

enum class PracticeKind {
    IDIOM,
    PHRASAL_VERB,
    ONE_WORD,
}

data class PracticeItem(
    val id: Int,
    val kind: PracticeKind,
    val prompt: String,
    val meaning: String,
    val example: String,
)

/**
 * Idioms + phrasal verbs + one-word substitutions (exam-style bank).
 * Used only inside the app (right-swipe practice), not on the home widget.
 */
object PracticeBank {
    val items: List<PracticeItem> = listOf(
    PracticeItem(1, PracticeKind.IDIOM, "A blessing in disguise", "Something good that isn't recognized at first", "Eg: “A blessing in disguise” — Something good that isn't recognized at first."),
    PracticeItem(2, PracticeKind.IDIOM, "A dime a dozen", "Very common and of little value", "Eg: “A dime a dozen” — Very common and of little value."),
    PracticeItem(3, PracticeKind.IDIOM, "Beat around the bush", "Avoid saying what you mean directly", "Eg: “Beat around the bush” — Avoid saying what you mean directly."),
    PracticeItem(4, PracticeKind.IDIOM, "Better late than never", "Doing something late is better than not doing it", "Eg: “Better late than never” — Doing something late is better than not doing it."),
    PracticeItem(5, PracticeKind.IDIOM, "Bite the bullet", "Face a difficult situation bravely", "Eg: “Bite the bullet” — Face a difficult situation bravely."),
    PracticeItem(6, PracticeKind.IDIOM, "Break the ice", "Make people feel more comfortable", "Eg: “Break the ice” — Make people feel more comfortable."),
    PracticeItem(7, PracticeKind.IDIOM, "Call it a day", "Stop working on something", "Eg: “Call it a day” — Stop working on something."),
    PracticeItem(8, PracticeKind.IDIOM, "Cut corners", "Do something poorly to save time or money", "Eg: “Cut corners” — Do something poorly to save time or money."),
    PracticeItem(9, PracticeKind.IDIOM, "Get out of hand", "Become uncontrolled", "Eg: “Get out of hand” — Become uncontrolled."),
    PracticeItem(10, PracticeKind.IDIOM, "Hit the nail on the head", "Describe exactly what is causing a situation", "Eg: “Hit the nail on the head” — Describe exactly what is causing a situation."),
    PracticeItem(11, PracticeKind.IDIOM, "Let the cat out of the bag", "Reveal a secret", "Eg: “Let the cat out of the bag” — Reveal a secret."),
    PracticeItem(12, PracticeKind.IDIOM, "Miss the boat", "Be too late for an opportunity", "Eg: “Miss the boat” — Be too late for an opportunity."),
    PracticeItem(13, PracticeKind.IDIOM, "On the ball", "Doing a good job; alert", "Eg: “On the ball” — Doing a good job; alert."),
    PracticeItem(14, PracticeKind.IDIOM, "Pull someone's leg", "Joke with someone", "Eg: “Pull someone's leg” — Joke with someone."),
    PracticeItem(15, PracticeKind.IDIOM, "Speak of the devil", "The person being discussed appears", "Eg: “Speak of the devil” — The person being discussed appears."),
    PracticeItem(16, PracticeKind.IDIOM, "The ball is in your court", "It is your decision or responsibility now", "Eg: “The ball is in your court” — It is your decision or responsibility now."),
    PracticeItem(17, PracticeKind.IDIOM, "Under the weather", "Feeling ill", "Eg: “Under the weather” — Feeling ill."),
    PracticeItem(18, PracticeKind.IDIOM, "Once in a blue moon", "Very rarely", "Eg: “Once in a blue moon” — Very rarely."),
    PracticeItem(19, PracticeKind.IDIOM, "Costs an arm and a leg", "Very expensive", "Eg: “Costs an arm and a leg” — Very expensive."),
    PracticeItem(20, PracticeKind.IDIOM, "Burn the midnight oil", "Work late into the night", "Eg: “Burn the midnight oil” — Work late into the night."),
    PracticeItem(21, PracticeKind.IDIOM, "Cry over spilt milk", "Waste time worrying about the past", "Eg: “Cry over spilt milk” — Waste time worrying about the past."),
    PracticeItem(22, PracticeKind.IDIOM, "Add fuel to the fire", "Make a bad situation worse", "Eg: “Add fuel to the fire” — Make a bad situation worse."),
    PracticeItem(23, PracticeKind.IDIOM, "At the drop of a hat", "Immediately; without hesitation", "Eg: “At the drop of a hat” — Immediately; without hesitation."),
    PracticeItem(24, PracticeKind.IDIOM, "Back to the drawing board", "Start again after a failure", "Eg: “Back to the drawing board” — Start again after a failure."),
    PracticeItem(25, PracticeKind.IDIOM, "Barking up the wrong tree", "Pursuing a mistaken approach", "Eg: “Barking up the wrong tree” — Pursuing a mistaken approach."),
    PracticeItem(26, PracticeKind.IDIOM, "Bend over backwards", "Try very hard to help", "Eg: “Bend over backwards” — Try very hard to help."),
    PracticeItem(27, PracticeKind.IDIOM, "Bite off more than you can chew", "Take on too much", "Eg: “Bite off more than you can chew” — Take on too much."),
    PracticeItem(28, PracticeKind.IDIOM, "Blow off steam", "Release pent-up energy or emotion", "Eg: “Blow off steam” — Release pent-up energy or emotion."),
    PracticeItem(29, PracticeKind.IDIOM, "Break a leg", "Good luck", "Eg: “Break a leg” — Good luck."),
    PracticeItem(30, PracticeKind.IDIOM, "By the skin of your teeth", "Only just succeed", "Eg: “By the skin of your teeth” — Only just succeed."),
    PracticeItem(31, PracticeKind.IDIOM, "Caught between two stools", "Difficulty choosing between two options", "Eg: “Caught between two stools” — Difficulty choosing between two options."),
    PracticeItem(32, PracticeKind.IDIOM, "Cross that bridge when you come to it", "Deal with a problem when it arises", "Eg: “Cross that bridge when you come to it” — Deal with a problem when it arises."),
    PracticeItem(33, PracticeKind.IDIOM, "Cut the mustard", "Reach the required standard", "Eg: “Cut the mustard” — Reach the required standard."),
    PracticeItem(34, PracticeKind.IDIOM, "Devil's advocate", "Argue the opposite for the sake of debate", "Eg: “Devil's advocate” — Argue the opposite for the sake of debate."),
    PracticeItem(35, PracticeKind.IDIOM, "Don't count your chickens", "Don't assume success too early", "Eg: “Don't count your chickens” — Don't assume success too early."),
    PracticeItem(36, PracticeKind.IDIOM, "Don't put all your eggs in one basket", "Don't risk everything on one plan", "Eg: “Don't put all your eggs in one basket” — Don't risk everything on one plan."),
    PracticeItem(37, PracticeKind.IDIOM, "Every cloud has a silver lining", "There is hope in every bad situation", "Eg: “Every cloud has a silver lining” — There is hope in every bad situation."),
    PracticeItem(38, PracticeKind.IDIOM, "Feel a bit under the weather", "Feel slightly ill", "Eg: “Feel a bit under the weather” — Feel slightly ill."),
    PracticeItem(39, PracticeKind.IDIOM, "Give someone the benefit of the doubt", "Believe someone despite uncertainty", "Eg: “Give someone the benefit of the doubt” — Believe someone despite uncertainty."),
    PracticeItem(40, PracticeKind.IDIOM, "Go the extra mile", "Make a special effort", "Eg: “Go the extra mile” — Make a special effort."),
    PracticeItem(41, PracticeKind.IDIOM, "Hang in there", "Don't give up", "Eg: “Hang in there” — Don't give up."),
    PracticeItem(42, PracticeKind.IDIOM, "Hit the sack", "Go to bed", "Eg: “Hit the sack” — Go to bed."),
    PracticeItem(43, PracticeKind.IDIOM, "In hot water", "In trouble", "Eg: “In hot water” — In trouble."),
    PracticeItem(44, PracticeKind.IDIOM, "It takes two to tango", "Both people are responsible", "Eg: “It takes two to tango” — Both people are responsible."),
    PracticeItem(45, PracticeKind.IDIOM, "Jump on the bandwagon", "Join a popular activity", "Eg: “Jump on the bandwagon” — Join a popular activity."),
    PracticeItem(46, PracticeKind.IDIOM, "Keep your chin up", "Stay positive", "Eg: “Keep your chin up” — Stay positive."),
    PracticeItem(47, PracticeKind.IDIOM, "Kill two birds with one stone", "Achieve two goals with one action", "Eg: “Kill two birds with one stone” — Achieve two goals with one action."),
    PracticeItem(48, PracticeKind.IDIOM, "Let sleeping dogs lie", "Avoid restarting an old conflict", "Eg: “Let sleeping dogs lie” — Avoid restarting an old conflict."),
    PracticeItem(49, PracticeKind.IDIOM, "Make a long story short", "Tell something briefly", "Eg: “Make a long story short” — Tell something briefly."),
    PracticeItem(50, PracticeKind.IDIOM, "No pain, no gain", "Effort is needed for success", "Eg: “No pain, no gain” — Effort is needed for success."),
    PracticeItem(51, PracticeKind.IDIOM, "On thin ice", "In a risky situation", "Eg: “On thin ice” — In a risky situation."),
    PracticeItem(52, PracticeKind.IDIOM, "Piece of cake", "Very easy", "Eg: “Piece of cake” — Very easy."),
    PracticeItem(53, PracticeKind.IDIOM, "Pull yourself together", "Calm down and act sensibly", "Eg: “Pull yourself together” — Calm down and act sensibly."),
    PracticeItem(54, PracticeKind.IDIOM, "See eye to eye", "Agree fully", "Eg: “See eye to eye” — Agree fully."),
    PracticeItem(55, PracticeKind.IDIOM, "Sit on the fence", "Avoid taking a side", "Eg: “Sit on the fence” — Avoid taking a side."),
    PracticeItem(56, PracticeKind.IDIOM, "Steal someone's thunder", "Take attention from someone else's success", "Eg: “Steal someone's thunder” — Take attention from someone else's success."),
    PracticeItem(57, PracticeKind.IDIOM, "Take it with a pinch of salt", "Don't take something too seriously", "Eg: “Take it with a pinch of salt” — Don't take something too seriously."),
    PracticeItem(58, PracticeKind.IDIOM, "The best of both worlds", "Enjoy benefits of two different things", "Eg: “The best of both worlds” — Enjoy benefits of two different things."),
    PracticeItem(59, PracticeKind.IDIOM, "The elephant in the room", "An obvious problem nobody discusses", "Eg: “The elephant in the room” — An obvious problem nobody discusses."),
    PracticeItem(60, PracticeKind.IDIOM, "Throw in the towel", "Give up", "Eg: “Throw in the towel” — Give up."),
    PracticeItem(61, PracticeKind.IDIOM, "Time flies", "Time passes quickly", "Eg: “Time flies” — Time passes quickly."),
    PracticeItem(62, PracticeKind.IDIOM, "To make matters worse", "To worsen a bad situation", "Eg: “To make matters worse” — To worsen a bad situation."),
    PracticeItem(63, PracticeKind.IDIOM, "Up in the air", "Undecided", "Eg: “Up in the air” — Undecided."),
    PracticeItem(64, PracticeKind.IDIOM, "Weather the storm", "Survive a difficult period", "Eg: “Weather the storm” — Survive a difficult period."),
    PracticeItem(65, PracticeKind.IDIOM, "Wrap your head around something", "Understand something complicated", "Eg: “Wrap your head around something” — Understand something complicated."),
    PracticeItem(66, PracticeKind.IDIOM, "Your guess is as good as mine", "I don't know either", "Eg: “Your guess is as good as mine” — I don't know either."),
    PracticeItem(67, PracticeKind.IDIOM, "A hot potato", "A controversial issue", "Eg: “A hot potato” — A controversial issue."),
    PracticeItem(68, PracticeKind.IDIOM, "Actions speak louder than words", "What you do matters more than what you say", "Eg: “Actions speak louder than words” — What you do matters more than what you say."),
    PracticeItem(69, PracticeKind.IDIOM, "An arm and a leg", "A large amount of money", "Eg: “An arm and a leg” — A large amount of money."),
    PracticeItem(70, PracticeKind.IDIOM, "At sixes and sevens", "In confusion", "Eg: “At sixes and sevens” — In confusion."),
    PracticeItem(71, PracticeKind.IDIOM, "Beat a dead horse", "Waste effort on a settled matter", "Eg: “Beat a dead horse” — Waste effort on a settled matter."),
    PracticeItem(72, PracticeKind.IDIOM, "Burn bridges", "Destroy relationships beyond repair", "Eg: “Burn bridges” — Destroy relationships beyond repair."),
    PracticeItem(73, PracticeKind.IDIOM, "Burst someone's bubble", "End someone's false hope", "Eg: “Burst someone's bubble” — End someone's false hope."),
    PracticeItem(74, PracticeKind.IDIOM, "By hook or by crook", "By any means necessary", "Eg: “By hook or by crook” — By any means necessary."),
    PracticeItem(75, PracticeKind.IDIOM, "Call a spade a spade", "Speak plainly", "Eg: “Call a spade a spade” — Speak plainly."),
    PracticeItem(76, PracticeKind.IDIOM, "Can't judge a book by its cover", "Appearance can be misleading", "Eg: “Can't judge a book by its cover” — Appearance can be misleading."),
    PracticeItem(77, PracticeKind.IDIOM, "Caught red-handed", "Caught while doing wrong", "Eg: “Caught red-handed” — Caught while doing wrong."),
    PracticeItem(78, PracticeKind.IDIOM, "Come rain or shine", "No matter what happens", "Eg: “Come rain or shine” — No matter what happens."),
    PracticeItem(79, PracticeKind.IDIOM, "Curiosity killed the cat", "Being too curious can cause trouble", "Eg: “Curiosity killed the cat” — Being too curious can cause trouble."),
    PracticeItem(80, PracticeKind.IDIOM, "Cut to the chase", "Get to the point", "Eg: “Cut to the chase” — Get to the point."),
    PracticeItem(81, PracticeKind.IDIOM, "Don't cry wolf", "Don't raise false alarms", "Eg: “Don't cry wolf” — Don't raise false alarms."),
    PracticeItem(82, PracticeKind.IDIOM, "Down to earth", "Practical and humble", "Eg: “Down to earth” — Practical and humble."),
    PracticeItem(83, PracticeKind.IDIOM, "Drive someone up the wall", "Annoy someone greatly", "Eg: “Drive someone up the wall” — Annoy someone greatly."),
    PracticeItem(84, PracticeKind.IDIOM, "Easier said than done", "Harder to do than to say", "Eg: “Easier said than done” — Harder to do than to say."),
    PracticeItem(85, PracticeKind.IDIOM, "Elbow room", "Enough space to move", "Eg: “Elbow room” — Enough space to move."),
    PracticeItem(86, PracticeKind.IDIOM, "Face the music", "Accept the consequences", "Eg: “Face the music” — Accept the consequences."),
    PracticeItem(87, PracticeKind.IDIOM, "Fish out of water", "Uncomfortable in a situation", "Eg: “Fish out of water” — Uncomfortable in a situation."),
    PracticeItem(88, PracticeKind.IDIOM, "Get a taste of your own medicine", "Receive the same treatment you gave others", "Eg: “Get a taste of your own medicine” — Receive the same treatment you gave others."),
    PracticeItem(89, PracticeKind.IDIOM, "Get cold feet", "Become too scared to continue", "Eg: “Get cold feet” — Become too scared to continue."),
    PracticeItem(90, PracticeKind.IDIOM, "Give the cold shoulder", "Ignore someone", "Eg: “Give the cold shoulder” — Ignore someone."),
    PracticeItem(91, PracticeKind.IDIOM, "Go down in flames", "Fail spectacularly", "Eg: “Go down in flames” — Fail spectacularly."),
    PracticeItem(92, PracticeKind.IDIOM, "Have your head in the clouds", "Be unrealistic", "Eg: “Have your head in the clouds” — Be unrealistic."),
    PracticeItem(93, PracticeKind.IDIOM, "In the same boat", "In the same difficult situation", "Eg: “In the same boat” — In the same difficult situation."),
    PracticeItem(94, PracticeKind.IDIOM, "Keep an eye on", "Watch carefully", "Eg: “Keep an eye on” — Watch carefully."),
    PracticeItem(95, PracticeKind.IDIOM, "Last but not least", "Important though mentioned last", "Eg: “Last but not least” — Important though mentioned last."),
    PracticeItem(96, PracticeKind.IDIOM, "Leave no stone unturned", "Search thoroughly", "Eg: “Leave no stone unturned” — Search thoroughly."),
    PracticeItem(97, PracticeKind.IDIOM, "Make ends meet", "Manage financially with difficulty", "Eg: “Make ends meet” — Manage financially with difficulty."),
    PracticeItem(98, PracticeKind.IDIOM, "Nip it in the bud", "Stop a problem early", "Eg: “Nip it in the bud” — Stop a problem early."),
    PracticeItem(99, PracticeKind.IDIOM, "Out of the blue", "Unexpectedly", "Eg: “Out of the blue” — Unexpectedly."),
    PracticeItem(100, PracticeKind.IDIOM, "Play it by ear", "Decide as you go", "Eg: “Play it by ear” — Decide as you go."),
    PracticeItem(101, PracticeKind.IDIOM, "Put all your eggs in one basket", "Depend on a single plan", "Eg: “Put all your eggs in one basket” — Depend on a single plan."),
    PracticeItem(102, PracticeKind.IDIOM, "Rome wasn't built in a day", "Important work takes time", "Eg: “Rome wasn't built in a day” — Important work takes time."),
    PracticeItem(103, PracticeKind.IDIOM, "Spill the beans", "Reveal a secret", "Eg: “Spill the beans” — Reveal a secret."),
    PracticeItem(104, PracticeKind.IDIOM, "Take the bull by the horns", "Deal with a problem directly", "Eg: “Take the bull by the horns” — Deal with a problem directly."),
    PracticeItem(105, PracticeKind.IDIOM, "Through thick and thin", "In good and bad times", "Eg: “Through thick and thin” — In good and bad times."),
    PracticeItem(106, PracticeKind.IDIOM, "Turn a blind eye", "Ignore something deliberately", "Eg: “Turn a blind eye” — Ignore something deliberately."),
    PracticeItem(107, PracticeKind.IDIOM, "When pigs fly", "Something that will never happen", "Eg: “When pigs fly” — Something that will never happen."),
    PracticeItem(108, PracticeKind.IDIOM, "A penny for your thoughts", "Tell me what you are thinking", "Eg: “A penny for your thoughts” — Tell me what you are thinking."),
    PracticeItem(109, PracticeKind.IDIOM, "Against the clock", "Rushed for time", "Eg: “Against the clock” — Rushed for time."),
    PracticeItem(110, PracticeKind.IDIOM, "All ears", "Listening carefully", "Eg: “All ears” — Listening carefully."),
    PracticeItem(111, PracticeKind.IDIOM, "Apple of one's eye", "Someone cherished", "Eg: “Apple of one's eye” — Someone cherished."),
    PracticeItem(112, PracticeKind.IDIOM, "As busy as a bee", "Very busy", "Eg: “As busy as a bee” — Very busy."),
    PracticeItem(113, PracticeKind.IDIOM, "At one's wit's end", "So worried that one doesn't know what to do", "Eg: “At one's wit's end” — So worried that one doesn't know what to do."),
    PracticeItem(114, PracticeKind.IDIOM, "Back against the wall", "In a difficult situation with few options", "Eg: “Back against the wall” — In a difficult situation with few options."),
    PracticeItem(115, PracticeKind.IDIOM, "Bark is worse than bite", "Sound more threatening than they are", "Eg: “Bark is worse than bite” — Sound more threatening than they are."),
    PracticeItem(116, PracticeKind.IDIOM, "Birds of a feather flock together", "Similar people stay together", "Eg: “Birds of a feather flock together” — Similar people stay together."),
    PracticeItem(117, PracticeKind.IDIOM, "Bite the dust", "Fail or die", "Eg: “Bite the dust” — Fail or die."),
    PracticeItem(118, PracticeKind.IDIOM, "Black sheep", "A disgraceful member of a group", "Eg: “Black sheep” — A disgraceful member of a group."),
    PracticeItem(119, PracticeKind.IDIOM, "Blessing in disguise", "An apparent misfortune that becomes good", "Eg: “Blessing in disguise” — An apparent misfortune that becomes good."),
    PracticeItem(120, PracticeKind.IDIOM, "Blow one's own trumpet", "Boast about oneself", "Eg: “Blow one's own trumpet” — Boast about oneself."),
    PracticeItem(121, PracticeKind.IDIOM, "Born with a silver spoon", "Born into wealth", "Eg: “Born with a silver spoon” — Born into wealth."),
    PracticeItem(122, PracticeKind.IDIOM, "Break the news", "Inform someone of important news", "Eg: “Break the news” — Inform someone of important news."),
    PracticeItem(123, PracticeKind.IDIOM, "Burn the candle at both ends", "Overwork by day and night", "Eg: “Burn the candle at both ends” — Overwork by day and night."),
    PracticeItem(124, PracticeKind.IDIOM, "Bury the hatchet", "End a quarrel", "Eg: “Bury the hatchet” — End a quarrel."),
    PracticeItem(125, PracticeKind.IDIOM, "By leaps and bounds", "Very quickly", "Eg: “By leaps and bounds” — Very quickly."),
    PracticeItem(126, PracticeKind.IDIOM, "Call off", "Cancel", "Eg: “Call off” — Cancel."),
    PracticeItem(127, PracticeKind.IDIOM, "Cast pearls before swine", "Offer valuable things to those who can't appreciate them", "Eg: “Cast pearls before swine” — Offer valuable things to those who can't appreciate them."),
    PracticeItem(128, PracticeKind.IDIOM, "Catch someone red-handed", "Catch someone in the act", "Eg: “Catch someone red-handed” — Catch someone in the act."),
    PracticeItem(129, PracticeKind.IDIOM, "Chip off the old block", "Child resembling a parent", "Eg: “Chip off the old block” — Child resembling a parent."),
    PracticeItem(130, PracticeKind.IDIOM, "Close shave", "Narrow escape", "Eg: “Close shave” — Narrow escape."),
    PracticeItem(131, PracticeKind.IDIOM, "Come to terms with", "Accept a difficult reality", "Eg: “Come to terms with” — Accept a difficult reality."),
    PracticeItem(132, PracticeKind.IDIOM, "Cook someone's goose", "Spoil someone's plans", "Eg: “Cook someone's goose” — Spoil someone's plans."),
    PracticeItem(133, PracticeKind.IDIOM, "Crocodile tears", "Fake sorrow", "Eg: “Crocodile tears” — Fake sorrow."),
    PracticeItem(134, PracticeKind.IDIOM, "Cut a sorry figure", "Make a poor impression", "Eg: “Cut a sorry figure” — Make a poor impression."),
    PracticeItem(135, PracticeKind.IDIOM, "Dark horse", "An unexpected winner", "Eg: “Dark horse” — An unexpected winner."),
    PracticeItem(136, PracticeKind.IDIOM, "Dead letter", "A law no longer enforced", "Eg: “Dead letter” — A law no longer enforced."),
    PracticeItem(137, PracticeKind.IDIOM, "Die in harness", "Die while still working", "Eg: “Die in harness” — Die while still working."),
    PracticeItem(138, PracticeKind.IDIOM, "Don't look a gift horse in the mouth", "Don't criticize a gift", "Eg: “Don't look a gift horse in the mouth” — Don't criticize a gift."),
    PracticeItem(139, PracticeKind.IDIOM, "Draw a blank", "Fail to remember or find something", "Eg: “Draw a blank” — Fail to remember or find something."),
    PracticeItem(140, PracticeKind.IDIOM, "Drive home", "Make a point clearly", "Eg: “Drive home” — Make a point clearly."),
    PracticeItem(141, PracticeKind.IDIOM, "Dutch courage", "Courage from alcohol", "Eg: “Dutch courage” — Courage from alcohol."),
    PracticeItem(142, PracticeKind.IDIOM, "Eat humble pie", "Admit a mistake humbly", "Eg: “Eat humble pie” — Admit a mistake humbly."),
    PracticeItem(143, PracticeKind.IDIOM, "End in smoke", "Come to nothing", "Eg: “End in smoke” — Come to nothing."),
    PracticeItem(144, PracticeKind.IDIOM, "Fair and square", "Honest and just", "Eg: “Fair and square” — Honest and just."),
    PracticeItem(145, PracticeKind.IDIOM, "Feather in one's cap", "An achievement to be proud of", "Eg: “Feather in one's cap” — An achievement to be proud of."),
    PracticeItem(146, PracticeKind.IDIOM, "Fish in troubled waters", "Take advantage of a crisis", "Eg: “Fish in troubled waters” — Take advantage of a crisis."),
    PracticeItem(147, PracticeKind.IDIOM, "Flash in the pan", "Brief success that doesn't last", "Eg: “Flash in the pan” — Brief success that doesn't last."),
    PracticeItem(148, PracticeKind.IDIOM, "Flesh and blood", "Human nature; close family", "Eg: “Flesh and blood” — Human nature; close family."),
    PracticeItem(149, PracticeKind.IDIOM, "Fly off the handle", "Lose temper suddenly", "Eg: “Fly off the handle” — Lose temper suddenly."),
    PracticeItem(150, PracticeKind.IDIOM, "Follow suit", "Do the same as others", "Eg: “Follow suit” — Do the same as others."),
    PracticeItem(151, PracticeKind.IDIOM, "Foot the bill", "Pay the cost", "Eg: “Foot the bill” — Pay the cost."),
    PracticeItem(152, PracticeKind.IDIOM, "From pillar to post", "From one place to another repeatedly", "Eg: “From pillar to post” — From one place to another repeatedly."),
    PracticeItem(153, PracticeKind.IDIOM, "Get the better of", "Defeat or overcome", "Eg: “Get the better of” — Defeat or overcome."),
    PracticeItem(154, PracticeKind.IDIOM, "Give a wide berth", "Avoid", "Eg: “Give a wide berth” — Avoid."),
    PracticeItem(155, PracticeKind.IDIOM, "Go against the grain", "Go against natural tendency", "Eg: “Go against the grain” — Go against natural tendency."),
    PracticeItem(156, PracticeKind.IDIOM, "Go scot-free", "Escape without punishment", "Eg: “Go scot-free” — Escape without punishment."),
    PracticeItem(157, PracticeKind.IDIOM, "Grease someone's palm", "Bribe someone", "Eg: “Grease someone's palm” — Bribe someone."),
    PracticeItem(158, PracticeKind.IDIOM, "Hand in glove", "In close association", "Eg: “Hand in glove” — In close association."),
    PracticeItem(159, PracticeKind.IDIOM, "Hard and fast", "Strict and unchangeable", "Eg: “Hard and fast” — Strict and unchangeable."),
    PracticeItem(160, PracticeKind.IDIOM, "Have an axe to grind", "Have a private motive", "Eg: “Have an axe to grind” — Have a private motive."),
    PracticeItem(161, PracticeKind.IDIOM, "Hit below the belt", "Act unfairly", "Eg: “Hit below the belt” — Act unfairly."),
    PracticeItem(162, PracticeKind.IDIOM, "Hold water", "Appear logical or true", "Eg: “Hold water” — Appear logical or true."),
    PracticeItem(163, PracticeKind.IDIOM, "Hue and cry", "Public outcry", "Eg: “Hue and cry” — Public outcry."),
    PracticeItem(164, PracticeKind.IDIOM, "In a nutshell", "Briefly", "Eg: “In a nutshell” — Briefly."),
    PracticeItem(165, PracticeKind.IDIOM, "In cold blood", "Deliberately without emotion", "Eg: “In cold blood” — Deliberately without emotion."),
    PracticeItem(166, PracticeKind.IDIOM, "In deep water", "In serious trouble", "Eg: “In deep water” — In serious trouble."),
    PracticeItem(167, PracticeKind.IDIOM, "In the nick of time", "Just in time", "Eg: “In the nick of time” — Just in time."),
    PracticeItem(168, PracticeKind.IDIOM, "Ins and outs", "Detailed points", "Eg: “Ins and outs” — Detailed points."),
    PracticeItem(169, PracticeKind.IDIOM, "Keep body and soul together", "Survive with basic needs", "Eg: “Keep body and soul together” — Survive with basic needs."),
    PracticeItem(170, PracticeKind.IDIOM, "Keep the wolf from the door", "Avoid starvation or poverty", "Eg: “Keep the wolf from the door” — Avoid starvation or poverty."),
    PracticeItem(171, PracticeKind.IDIOM, "Laughing stock", "Object of ridicule", "Eg: “Laughing stock” — Object of ridicule."),
    PracticeItem(172, PracticeKind.IDIOM, "Lead by the nose", "Control someone completely", "Eg: “Lead by the nose” — Control someone completely."),
    PracticeItem(173, PracticeKind.IDIOM, "Leave in the lurch", "Abandon in difficulty", "Eg: “Leave in the lurch” — Abandon in difficulty."),
    PracticeItem(174, PracticeKind.IDIOM, "Let bygones be bygones", "Forget past quarrels", "Eg: “Let bygones be bygones” — Forget past quarrels."),
    PracticeItem(175, PracticeKind.IDIOM, "Lion's share", "The largest part", "Eg: “Lion's share” — The largest part."),
    PracticeItem(176, PracticeKind.IDIOM, "Live from hand to mouth", "Live with barely enough money", "Eg: “Live from hand to mouth” — Live with barely enough money."),
    PracticeItem(177, PracticeKind.IDIOM, "Look down upon", "Regard with contempt", "Eg: “Look down upon” — Regard with contempt."),
    PracticeItem(178, PracticeKind.IDIOM, "Make a clean breast of", "Confess fully", "Eg: “Make a clean breast of” — Confess fully."),
    PracticeItem(179, PracticeKind.IDIOM, "Make hay while the sun shines", "Use an opportunity while it lasts", "Eg: “Make hay while the sun shines” — Use an opportunity while it lasts."),
    PracticeItem(180, PracticeKind.IDIOM, "Man of letters", "A scholarly writer", "Eg: “Man of letters” — A scholarly writer."),
    PracticeItem(181, PracticeKind.IDIOM, "Null and void", "Invalid", "Eg: “Null and void” — Invalid."),
    PracticeItem(182, PracticeKind.IDIOM, "On the spur of the moment", "Suddenly; without planning", "Eg: “On the spur of the moment” — Suddenly; without planning."),
    PracticeItem(183, PracticeKind.IDIOM, "Out of the woods", "Out of danger", "Eg: “Out of the woods” — Out of danger."),
    PracticeItem(184, PracticeKind.IDIOM, "Pay through the nose", "Pay too much", "Eg: “Pay through the nose” — Pay too much."),
    PracticeItem(185, PracticeKind.IDIOM, "Pick holes in", "Find faults", "Eg: “Pick holes in” — Find faults."),
    PracticeItem(186, PracticeKind.IDIOM, "Play second fiddle", "Take a less important role", "Eg: “Play second fiddle” — Take a less important role."),
    PracticeItem(187, PracticeKind.IDIOM, "Pour oil on troubled waters", "Calm a conflict", "Eg: “Pour oil on troubled waters” — Calm a conflict."),
    PracticeItem(188, PracticeKind.IDIOM, "Pros and cons", "Advantages and disadvantages", "Eg: “Pros and cons” — Advantages and disadvantages."),
    PracticeItem(189, PracticeKind.IDIOM, "Put the cart before the horse", "Do things in the wrong order", "Eg: “Put the cart before the horse” — Do things in the wrong order."),
    PracticeItem(190, PracticeKind.IDIOM, "Rain cats and dogs", "Rain heavily", "Eg: “Rain cats and dogs” — Rain heavily."),
    PracticeItem(191, PracticeKind.IDIOM, "Read between the lines", "Find a hidden meaning", "Eg: “Read between the lines” — Find a hidden meaning."),
    PracticeItem(192, PracticeKind.IDIOM, "Red tape", "Official formality causing delay", "Eg: “Red tape” — Official formality causing delay."),
    PracticeItem(193, PracticeKind.IDIOM, "Rest on one's laurels", "Be satisfied with past success", "Eg: “Rest on one's laurels” — Be satisfied with past success."),
    PracticeItem(194, PracticeKind.IDIOM, "Save for a rainy day", "Save money for hard times", "Eg: “Save for a rainy day” — Save money for hard times."),
    PracticeItem(195, PracticeKind.IDIOM, "Smell a rat", "Suspect something wrong", "Eg: “Smell a rat” — Suspect something wrong."),
    PracticeItem(196, PracticeKind.IDIOM, "Square peg in a round hole", "A misfit", "Eg: “Square peg in a round hole” — A misfit."),
    PracticeItem(197, PracticeKind.IDIOM, "Storm in a teacup", "Big fuss over a small matter", "Eg: “Storm in a teacup” — Big fuss over a small matter."),
    PracticeItem(198, PracticeKind.IDIOM, "Take to heart", "Be deeply affected", "Eg: “Take to heart” — Be deeply affected."),
    PracticeItem(199, PracticeKind.IDIOM, "Talk of the town", "The subject of much gossip", "Eg: “Talk of the town” — The subject of much gossip."),
    PracticeItem(200, PracticeKind.IDIOM, "Throw cold water on", "Discourage", "Eg: “Throw cold water on” — Discourage."),
    PracticeItem(201, PracticeKind.IDIOM, "Turn over a new leaf", "Start behaving better", "Eg: “Turn over a new leaf” — Start behaving better."),
    PracticeItem(202, PracticeKind.IDIOM, "Under one's thumb", "Under someone's control", "Eg: “Under one's thumb” — Under someone's control."),
    PracticeItem(203, PracticeKind.IDIOM, "White elephant", "A costly but useless possession", "Eg: “White elephant” — A costly but useless possession."),
    PracticeItem(204, PracticeKind.IDIOM, "Wild goose chase", "A pointless search", "Eg: “Wild goose chase” — A pointless search."),
    PracticeItem(205, PracticeKind.IDIOM, "With flying colours", "With great success", "Eg: “With flying colours” — With great success."),
    PracticeItem(206, PracticeKind.IDIOM, "Yeoman's service", "Excellent useful help", "Eg: “Yeoman's service” — Excellent useful help."),
    PracticeItem(207, PracticeKind.PHRASAL_VERB, "abide by", "accept and follow a rule", "Eg: They had to abide by before noon."),
    PracticeItem(208, PracticeKind.PHRASAL_VERB, "account for", "explain the reason for", "Eg: They had to account for before noon."),
    PracticeItem(209, PracticeKind.PHRASAL_VERB, "act up", "behave badly; malfunction", "Eg: They had to act up before noon."),
    PracticeItem(210, PracticeKind.PHRASAL_VERB, "add up", "make sense; calculate a total", "Eg: They had to add up before noon."),
    PracticeItem(211, PracticeKind.PHRASAL_VERB, "ask around", "ask many people for information", "Eg: They had to ask around before noon."),
    PracticeItem(212, PracticeKind.PHRASAL_VERB, "back up", "support; make a copy", "Eg: They had to back up before noon."),
    PracticeItem(213, PracticeKind.PHRASAL_VERB, "break down", "stop working; lose control emotionally", "Eg: They had to break down before noon."),
    PracticeItem(214, PracticeKind.PHRASAL_VERB, "break into", "enter by force", "Eg: They had to break into before noon."),
    PracticeItem(215, PracticeKind.PHRASAL_VERB, "break out", "start suddenly", "Eg: They had to break out before noon."),
    PracticeItem(216, PracticeKind.PHRASAL_VERB, "bring about", "cause to happen", "Eg: They had to bring about before noon."),
    PracticeItem(217, PracticeKind.PHRASAL_VERB, "bring up", "raise a topic; raise a child", "Eg: They had to bring up before noon."),
    PracticeItem(218, PracticeKind.PHRASAL_VERB, "call off", "cancel", "Eg: They had to call off before noon."),
    PracticeItem(219, PracticeKind.PHRASAL_VERB, "call on", "visit; ask to speak", "Eg: They had to call on before noon."),
    PracticeItem(220, PracticeKind.PHRASAL_VERB, "carry on", "continue", "Eg: They had to carry on before noon."),
    PracticeItem(221, PracticeKind.PHRASAL_VERB, "catch up", "reach the same level", "Eg: They had to catch up before noon."),
    PracticeItem(222, PracticeKind.PHRASAL_VERB, "check in", "register on arrival", "Eg: They had to check in before noon."),
    PracticeItem(223, PracticeKind.PHRASAL_VERB, "check out", "leave a hotel; examine", "Eg: They had to check out before noon."),
    PracticeItem(224, PracticeKind.PHRASAL_VERB, "come across", "find by chance", "Eg: They had to come across before noon."),
    PracticeItem(225, PracticeKind.PHRASAL_VERB, "come forward", "offer help or information", "Eg: They had to come forward before noon."),
    PracticeItem(226, PracticeKind.PHRASAL_VERB, "come up with", "think of an idea", "Eg: They had to come up with before noon."),
    PracticeItem(227, PracticeKind.PHRASAL_VERB, "cut down on", "reduce", "Eg: They had to cut down on before noon."),
    PracticeItem(228, PracticeKind.PHRASAL_VERB, "cut off", "disconnect; isolate", "Eg: They had to cut off before noon."),
    PracticeItem(229, PracticeKind.PHRASAL_VERB, "do away with", "abolish", "Eg: They had to do away with before noon."),
    PracticeItem(230, PracticeKind.PHRASAL_VERB, "drop by", "visit briefly", "Eg: They had to drop by before noon."),
    PracticeItem(231, PracticeKind.PHRASAL_VERB, "drop out", "leave school or a course", "Eg: They had to drop out before noon."),
    PracticeItem(232, PracticeKind.PHRASAL_VERB, "end up", "finally be in a situation", "Eg: They had to end up before noon."),
    PracticeItem(233, PracticeKind.PHRASAL_VERB, "fall apart", "break into pieces; collapse", "Eg: They had to fall apart before noon."),
    PracticeItem(234, PracticeKind.PHRASAL_VERB, "figure out", "understand after thinking", "Eg: They had to figure out before noon."),
    PracticeItem(235, PracticeKind.PHRASAL_VERB, "fill in", "complete a form; substitute temporarily", "Eg: They had to fill in before noon."),
    PracticeItem(236, PracticeKind.PHRASAL_VERB, "find out", "discover information", "Eg: They had to find out before noon."),
    PracticeItem(237, PracticeKind.PHRASAL_VERB, "get along", "have a good relationship", "Eg: They had to get along before noon."),
    PracticeItem(238, PracticeKind.PHRASAL_VERB, "get away", "escape", "Eg: They had to get away before noon."),
    PracticeItem(239, PracticeKind.PHRASAL_VERB, "get over", "recover from", "Eg: They had to get over before noon."),
    PracticeItem(240, PracticeKind.PHRASAL_VERB, "get through", "succeed in contacting; finish", "Eg: They had to get through before noon."),
    PracticeItem(241, PracticeKind.PHRASAL_VERB, "give away", "donate; reveal a secret", "Eg: They had to give away before noon."),
    PracticeItem(242, PracticeKind.PHRASAL_VERB, "give in", "surrender; yield", "Eg: They had to give in before noon."),
    PracticeItem(243, PracticeKind.PHRASAL_VERB, "give up", "stop trying", "Eg: They had to give up before noon."),
    PracticeItem(244, PracticeKind.PHRASAL_VERB, "go ahead", "proceed", "Eg: They had to go ahead before noon."),
    PracticeItem(245, PracticeKind.PHRASAL_VERB, "go over", "review", "Eg: They had to go over before noon."),
    PracticeItem(246, PracticeKind.PHRASAL_VERB, "grow up", "become an adult", "Eg: They had to grow up before noon."),
    PracticeItem(247, PracticeKind.PHRASAL_VERB, "hand in", "submit", "Eg: They had to hand in before noon."),
    PracticeItem(248, PracticeKind.PHRASAL_VERB, "hang out", "spend time socially", "Eg: They had to hang out before noon."),
    PracticeItem(249, PracticeKind.PHRASAL_VERB, "hold on", "wait", "Eg: They had to hold on before noon."),
    PracticeItem(250, PracticeKind.PHRASAL_VERB, "keep on", "continue", "Eg: They had to keep on before noon."),
    PracticeItem(251, PracticeKind.PHRASAL_VERB, "keep up with", "stay at the same level as", "Eg: They had to keep up with before noon."),
    PracticeItem(252, PracticeKind.PHRASAL_VERB, "leave out", "omit", "Eg: They had to leave out before noon."),
    PracticeItem(253, PracticeKind.PHRASAL_VERB, "look after", "take care of", "Eg: They had to look after before noon."),
    PracticeItem(254, PracticeKind.PHRASAL_VERB, "look forward to", "await eagerly", "Eg: They had to look forward to before noon."),
    PracticeItem(255, PracticeKind.PHRASAL_VERB, "look into", "investigate", "Eg: They had to look into before noon."),
    PracticeItem(256, PracticeKind.PHRASAL_VERB, "look up", "search for information", "Eg: They had to look up before noon."),
    PracticeItem(257, PracticeKind.PHRASAL_VERB, "make up", "invent; reconcile", "Eg: They had to make up before noon."),
    PracticeItem(258, PracticeKind.PHRASAL_VERB, "pass away", "die", "Eg: They had to pass away before noon."),
    PracticeItem(259, PracticeKind.PHRASAL_VERB, "pass out", "faint", "Eg: They had to pass out before noon."),
    PracticeItem(260, PracticeKind.PHRASAL_VERB, "pick up", "collect; learn casually", "Eg: They had to pick up before noon."),
    PracticeItem(261, PracticeKind.PHRASAL_VERB, "point out", "indicate", "Eg: They had to point out before noon."),
    PracticeItem(262, PracticeKind.PHRASAL_VERB, "put off", "postpone", "Eg: They had to put off before noon."),
    PracticeItem(263, PracticeKind.PHRASAL_VERB, "put on", "wear; stage a show", "Eg: They had to put on before noon."),
    PracticeItem(264, PracticeKind.PHRASAL_VERB, "put up with", "tolerate", "Eg: They had to put up with before noon."),
    PracticeItem(265, PracticeKind.PHRASAL_VERB, "run into", "meet by chance", "Eg: They had to run into before noon."),
    PracticeItem(266, PracticeKind.PHRASAL_VERB, "run out of", "have none left", "Eg: They had to run out of before noon."),
    PracticeItem(267, PracticeKind.PHRASAL_VERB, "set up", "arrange; establish", "Eg: They had to set up before noon."),
    PracticeItem(268, PracticeKind.PHRASAL_VERB, "show up", "appear", "Eg: They had to show up before noon."),
    PracticeItem(269, PracticeKind.PHRASAL_VERB, "shut down", "close permanently; switch off", "Eg: They had to shut down before noon."),
    PracticeItem(270, PracticeKind.PHRASAL_VERB, "sort out", "organize; resolve", "Eg: They had to sort out before noon."),
    PracticeItem(271, PracticeKind.PHRASAL_VERB, "stand by", "support; be ready", "Eg: They had to stand by before noon."),
    PracticeItem(272, PracticeKind.PHRASAL_VERB, "take after", "resemble a family member", "Eg: They had to take after before noon."),
    PracticeItem(273, PracticeKind.PHRASAL_VERB, "take off", "leave the ground; become successful", "Eg: They had to take off before noon."),
    PracticeItem(274, PracticeKind.PHRASAL_VERB, "take over", "assume control", "Eg: They had to take over before noon."),
    PracticeItem(275, PracticeKind.PHRASAL_VERB, "turn down", "reject", "Eg: They had to turn down before noon."),
    PracticeItem(276, PracticeKind.PHRASAL_VERB, "turn up", "appear; increase volume", "Eg: They had to turn up before noon."),
    PracticeItem(277, PracticeKind.PHRASAL_VERB, "work out", "exercise; find a solution", "Eg: They had to work out before noon."),
    PracticeItem(278, PracticeKind.PHRASAL_VERB, "back out", "withdraw from an agreement", "Eg: They had to back out before noon."),
    PracticeItem(279, PracticeKind.PHRASAL_VERB, "blow up", "explode; become angry", "Eg: They had to blow up before noon."),
    PracticeItem(280, PracticeKind.PHRASAL_VERB, "break away", "escape from control", "Eg: They had to break away before noon."),
    PracticeItem(281, PracticeKind.PHRASAL_VERB, "break through", "overcome a barrier", "Eg: They had to break through before noon."),
    PracticeItem(282, PracticeKind.PHRASAL_VERB, "bring down", "cause to fall; reduce", "Eg: They had to bring down before noon."),
    PracticeItem(283, PracticeKind.PHRASAL_VERB, "bring forward", "present earlier", "Eg: They had to bring forward before noon."),
    PracticeItem(284, PracticeKind.PHRASAL_VERB, "brush up on", "improve knowledge of", "Eg: They had to brush up on before noon."),
    PracticeItem(285, PracticeKind.PHRASAL_VERB, "build up", "increase gradually", "Eg: They had to build up before noon."),
    PracticeItem(286, PracticeKind.PHRASAL_VERB, "bump into", "meet unexpectedly", "Eg: They had to bump into before noon."),
    PracticeItem(287, PracticeKind.PHRASAL_VERB, "call for", "require; demand", "Eg: They had to call for before noon."),
    PracticeItem(288, PracticeKind.PHRASAL_VERB, "calm down", "become less agitated", "Eg: They had to calm down before noon."),
    PracticeItem(289, PracticeKind.PHRASAL_VERB, "carry out", "perform a task", "Eg: They had to carry out before noon."),
    PracticeItem(290, PracticeKind.PHRASAL_VERB, "catch on", "become popular; understand", "Eg: They had to catch on before noon."),
    PracticeItem(291, PracticeKind.PHRASAL_VERB, "cheer up", "become happier", "Eg: They had to cheer up before noon."),
    PracticeItem(292, PracticeKind.PHRASAL_VERB, "clean up", "make tidy", "Eg: They had to clean up before noon."),
    PracticeItem(293, PracticeKind.PHRASAL_VERB, "clear up", "become understandable; weather improves", "Eg: They had to clear up before noon."),
    PracticeItem(294, PracticeKind.PHRASAL_VERB, "close down", "stop business permanently", "Eg: They had to close down before noon."),
    PracticeItem(295, PracticeKind.PHRASAL_VERB, "come about", "happen", "Eg: They had to come about before noon."),
    PracticeItem(296, PracticeKind.PHRASAL_VERB, "come down with", "become ill with", "Eg: They had to come down with before noon."),
    PracticeItem(297, PracticeKind.PHRASAL_VERB, "come into", "inherit", "Eg: They had to come into before noon."),
    PracticeItem(298, PracticeKind.PHRASAL_VERB, "count on", "rely on", "Eg: They had to count on before noon."),
    PracticeItem(299, PracticeKind.PHRASAL_VERB, "cross out", "draw a line through", "Eg: They had to cross out before noon."),
    PracticeItem(300, PracticeKind.PHRASAL_VERB, "cut back", "reduce spending", "Eg: They had to cut back before noon."),
    PracticeItem(301, PracticeKind.PHRASAL_VERB, "deal with", "handle", "Eg: They had to deal with before noon."),
    PracticeItem(302, PracticeKind.PHRASAL_VERB, "die down", "become quieter", "Eg: They had to die down before noon."),
    PracticeItem(303, PracticeKind.PHRASAL_VERB, "do over", "do again", "Eg: They had to do over before noon."),
    PracticeItem(304, PracticeKind.PHRASAL_VERB, "dress up", "wear formal clothes", "Eg: They had to dress up before noon."),
    PracticeItem(305, PracticeKind.PHRASAL_VERB, "drop off", "deliver; fall asleep", "Eg: They had to drop off before noon."),
    PracticeItem(306, PracticeKind.PHRASAL_VERB, "eat out", "dine at a restaurant", "Eg: They had to eat out before noon."),
    PracticeItem(307, PracticeKind.PHRASAL_VERB, "fall behind", "fail to keep up", "Eg: They had to fall behind before noon."),
    PracticeItem(308, PracticeKind.PHRASAL_VERB, "fall through", "fail to happen", "Eg: They had to fall through before noon."),
    PracticeItem(309, PracticeKind.PHRASAL_VERB, "fill up", "make full", "Eg: They had to fill up before noon."),
    PracticeItem(310, PracticeKind.PHRASAL_VERB, "get across", "communicate successfully", "Eg: They had to get across before noon."),
    PracticeItem(311, PracticeKind.PHRASAL_VERB, "get by", "manage with difficulty", "Eg: They had to get by before noon."),
    PracticeItem(312, PracticeKind.PHRASAL_VERB, "get in", "enter; arrive", "Eg: They had to get in before noon."),
    PracticeItem(313, PracticeKind.PHRASAL_VERB, "get on", "board; have a relationship", "Eg: They had to get on before noon."),
    PracticeItem(314, PracticeKind.PHRASAL_VERB, "give back", "return", "Eg: They had to give back before noon."),
    PracticeItem(315, PracticeKind.PHRASAL_VERB, "go after", "pursue", "Eg: They had to go after before noon."),
    PracticeItem(316, PracticeKind.PHRASAL_VERB, "go along with", "agree with", "Eg: They had to go along with before noon."),
    PracticeItem(317, PracticeKind.PHRASAL_VERB, "go back", "return", "Eg: They had to go back before noon."),
    PracticeItem(318, PracticeKind.PHRASAL_VERB, "go off", "explode; stop liking", "Eg: They had to go off before noon."),
    PracticeItem(319, PracticeKind.PHRASAL_VERB, "hand out", "distribute", "Eg: They had to hand out before noon."),
    PracticeItem(320, PracticeKind.PHRASAL_VERB, "hang up", "end a phone call", "Eg: They had to hang up before noon."),
    PracticeItem(321, PracticeKind.PHRASAL_VERB, "hold back", "restrain", "Eg: They had to hold back before noon."),
    PracticeItem(322, PracticeKind.PHRASAL_VERB, "hurry up", "go faster", "Eg: They had to hurry up before noon."),
    PracticeItem(323, PracticeKind.PHRASAL_VERB, "join in", "participate", "Eg: They had to join in before noon."),
    PracticeItem(324, PracticeKind.PHRASAL_VERB, "keep away", "avoid", "Eg: They had to keep away before noon."),
    PracticeItem(325, PracticeKind.PHRASAL_VERB, "let down", "disappoint", "Eg: They had to let down before noon."),
    PracticeItem(326, PracticeKind.PHRASAL_VERB, "let in", "allow to enter", "Eg: They had to let in before noon."),
    PracticeItem(327, PracticeKind.PHRASAL_VERB, "live on", "survive using", "Eg: They had to live on before noon."),
    PracticeItem(328, PracticeKind.PHRASAL_VERB, "log in", "access a system", "Eg: They had to log in before noon."),
    PracticeItem(329, PracticeKind.PHRASAL_VERB, "look out", "be careful", "Eg: They had to look out before noon."),
    PracticeItem(330, PracticeKind.PHRASAL_VERB, "make out", "discern; kiss", "Eg: They had to make out before noon."),
    PracticeItem(331, PracticeKind.PHRASAL_VERB, "mix up", "confuse", "Eg: They had to mix up before noon."),
    PracticeItem(332, PracticeKind.PHRASAL_VERB, "move in", "start living somewhere", "Eg: They had to move in before noon."),
    PracticeItem(333, PracticeKind.PHRASAL_VERB, "move on", "proceed to something new", "Eg: They had to move on before noon."),
    PracticeItem(334, PracticeKind.PHRASAL_VERB, "opt out", "choose not to participate", "Eg: They had to opt out before noon."),
    PracticeItem(335, PracticeKind.PHRASAL_VERB, "pass on", "give to the next person; die", "Eg: They had to pass on before noon."),
    PracticeItem(336, PracticeKind.PHRASAL_VERB, "pay back", "repay", "Eg: They had to pay back before noon."),
    PracticeItem(337, PracticeKind.PHRASAL_VERB, "pay off", "yield good results; finish paying", "Eg: They had to pay off before noon."),
    PracticeItem(338, PracticeKind.PHRASAL_VERB, "phase out", "gradually stop using", "Eg: They had to phase out before noon."),
    PracticeItem(339, PracticeKind.PHRASAL_VERB, "pull over", "stop a vehicle by the roadside", "Eg: They had to pull over before noon."),
    PracticeItem(340, PracticeKind.PHRASAL_VERB, "put away", "store", "Eg: They had to put away before noon."),
    PracticeItem(341, PracticeKind.PHRASAL_VERB, "put down", "criticize; write", "Eg: They had to put down before noon."),
    PracticeItem(342, PracticeKind.PHRASAL_VERB, "put through", "connect by phone", "Eg: They had to put through before noon."),
    PracticeItem(343, PracticeKind.PHRASAL_VERB, "rule out", "exclude as a possibility", "Eg: They had to rule out before noon."),
    PracticeItem(344, PracticeKind.PHRASAL_VERB, "run after", "chase", "Eg: They had to run after before noon."),
    PracticeItem(345, PracticeKind.PHRASAL_VERB, "run over", "hit with a vehicle; review quickly", "Eg: They had to run over before noon."),
    PracticeItem(346, PracticeKind.PHRASAL_VERB, "see off", "say goodbye at departure", "Eg: They had to see off before noon."),
    PracticeItem(347, PracticeKind.PHRASAL_VERB, "send for", "request someone to come", "Eg: They had to send for before noon."),
    PracticeItem(348, PracticeKind.PHRASAL_VERB, "set off", "begin a journey; cause", "Eg: They had to set off before noon."),
    PracticeItem(349, PracticeKind.PHRASAL_VERB, "settle down", "start a stable life", "Eg: They had to settle down before noon."),
    PracticeItem(350, PracticeKind.PHRASAL_VERB, "show off", "display proudly", "Eg: They had to show off before noon."),
    PracticeItem(351, PracticeKind.PHRASAL_VERB, "shut up", "stop talking", "Eg: They had to shut up before noon."),
    PracticeItem(352, PracticeKind.PHRASAL_VERB, "sign up", "register", "Eg: They had to sign up before noon."),
    PracticeItem(353, PracticeKind.PHRASAL_VERB, "sit down", "take a seat", "Eg: They had to sit down before noon."),
    PracticeItem(354, PracticeKind.PHRASAL_VERB, "slow down", "reduce speed", "Eg: They had to slow down before noon."),
    PracticeItem(355, PracticeKind.PHRASAL_VERB, "speak up", "talk louder; express opinion", "Eg: They had to speak up before noon."),
    PracticeItem(356, PracticeKind.PHRASAL_VERB, "stand out", "be noticeable", "Eg: They had to stand out before noon."),
    PracticeItem(357, PracticeKind.PHRASAL_VERB, "stand up", "rise to feet; fail to meet", "Eg: They had to stand up before noon."),
    PracticeItem(358, PracticeKind.PHRASAL_VERB, "stay up", "remain awake", "Eg: They had to stay up before noon."),
    PracticeItem(359, PracticeKind.PHRASAL_VERB, "stick to", "continue following", "Eg: They had to stick to before noon."),
    PracticeItem(360, PracticeKind.PHRASAL_VERB, "switch off", "turn off", "Eg: They had to switch off before noon."),
    PracticeItem(361, PracticeKind.PHRASAL_VERB, "take away", "remove", "Eg: They had to take away before noon."),
    PracticeItem(362, PracticeKind.PHRASAL_VERB, "take back", "retract; return", "Eg: They had to take back before noon."),
    PracticeItem(363, PracticeKind.PHRASAL_VERB, "take in", "understand; deceive", "Eg: They had to take in before noon."),
    PracticeItem(364, PracticeKind.PHRASAL_VERB, "take up", "start a hobby; occupy space", "Eg: They had to take up before noon."),
    PracticeItem(365, PracticeKind.PHRASAL_VERB, "talk over", "discuss thoroughly", "Eg: They had to talk over before noon."),
    PracticeItem(366, PracticeKind.PHRASAL_VERB, "tear up", "rip into pieces", "Eg: They had to tear up before noon."),
    PracticeItem(367, PracticeKind.PHRASAL_VERB, "think over", "consider carefully", "Eg: They had to think over before noon."),
    PracticeItem(368, PracticeKind.PHRASAL_VERB, "throw away", "discard", "Eg: They had to throw away before noon."),
    PracticeItem(369, PracticeKind.PHRASAL_VERB, "try on", "test clothing size", "Eg: They had to try on before noon."),
    PracticeItem(370, PracticeKind.PHRASAL_VERB, "turn into", "become", "Eg: They had to turn into before noon."),
    PracticeItem(371, PracticeKind.PHRASAL_VERB, "turn off", "switch off; cause dislike", "Eg: They had to turn off before noon."),
    PracticeItem(372, PracticeKind.PHRASAL_VERB, "turn on", "switch on", "Eg: They had to turn on before noon."),
    PracticeItem(373, PracticeKind.PHRASAL_VERB, "use up", "consume completely", "Eg: They had to use up before noon."),
    PracticeItem(374, PracticeKind.PHRASAL_VERB, "wake up", "stop sleeping", "Eg: They had to wake up before noon."),
    PracticeItem(375, PracticeKind.PHRASAL_VERB, "watch out", "be careful", "Eg: They had to watch out before noon."),
    PracticeItem(376, PracticeKind.PHRASAL_VERB, "wear out", "become unusable from use", "Eg: They had to wear out before noon."),
    PracticeItem(377, PracticeKind.PHRASAL_VERB, "work on", "try to improve", "Eg: They had to work on before noon."),
    PracticeItem(378, PracticeKind.PHRASAL_VERB, "write down", "record in writing", "Eg: They had to write down before noon."),
    PracticeItem(379, PracticeKind.PHRASAL_VERB, "zip up", "close with a zip", "Eg: They had to zip up before noon."),
    PracticeItem(380, PracticeKind.PHRASAL_VERB, "act on", "take action because of", "Eg: They had to act on before noon."),
    PracticeItem(381, PracticeKind.PHRASAL_VERB, "aim at", "direct toward a target", "Eg: They had to aim at before noon."),
    PracticeItem(382, PracticeKind.PHRASAL_VERB, "amount to", "add up to; be equal to", "Eg: They had to amount to before noon."),
    PracticeItem(383, PracticeKind.PHRASAL_VERB, "answer for", "be responsible for", "Eg: They had to answer for before noon."),
    PracticeItem(384, PracticeKind.PHRASAL_VERB, "appeal to", "attract; request formally", "Eg: They had to appeal to before noon."),
    PracticeItem(385, PracticeKind.PHRASAL_VERB, "apply for", "make a formal request for", "Eg: They had to apply for before noon."),
    PracticeItem(386, PracticeKind.PHRASAL_VERB, "approve of", "regard favorably", "Eg: They had to approve of before noon."),
    PracticeItem(387, PracticeKind.PHRASAL_VERB, "argue with", "disagree verbally with", "Eg: They had to argue with before noon."),
    PracticeItem(388, PracticeKind.PHRASAL_VERB, "arrive at", "reach a place or conclusion", "Eg: They had to arrive at before noon."),
    PracticeItem(389, PracticeKind.PHRASAL_VERB, "ask for", "request", "Eg: They had to ask for before noon."),
    PracticeItem(390, PracticeKind.PHRASAL_VERB, "attach to", "connect to", "Eg: They had to attach to before noon."),
    PracticeItem(391, PracticeKind.PHRASAL_VERB, "attend to", "deal with", "Eg: They had to attend to before noon."),
    PracticeItem(392, PracticeKind.PHRASAL_VERB, "attribute to", "regard as caused by", "Eg: They had to attribute to before noon."),
    PracticeItem(393, PracticeKind.PHRASAL_VERB, "base on", "use as foundation", "Eg: They had to base on before noon."),
    PracticeItem(394, PracticeKind.PHRASAL_VERB, "believe in", "have faith in", "Eg: They had to believe in before noon."),
    PracticeItem(395, PracticeKind.PHRASAL_VERB, "belong to", "be the property of", "Eg: They had to belong to before noon."),
    PracticeItem(396, PracticeKind.PHRASAL_VERB, "benefit from", "gain advantage from", "Eg: They had to benefit from before noon."),
    PracticeItem(397, PracticeKind.PHRASAL_VERB, "blame for", "hold responsible for", "Eg: They had to blame for before noon."),
    PracticeItem(398, PracticeKind.PHRASAL_VERB, "boast of", "speak proudly of", "Eg: They had to boast of before noon."),
    PracticeItem(399, PracticeKind.PHRASAL_VERB, "border on", "be close to", "Eg: They had to border on before noon."),
    PracticeItem(400, PracticeKind.PHRASAL_VERB, "care for", "look after; like", "Eg: They had to care for before noon."),
    PracticeItem(401, PracticeKind.PHRASAL_VERB, "charge with", "accuse of", "Eg: They had to charge with before noon."),
    PracticeItem(402, PracticeKind.PHRASAL_VERB, "collide with", "crash into", "Eg: They had to collide with before noon."),
    PracticeItem(403, PracticeKind.PHRASAL_VERB, "comment on", "remark about", "Eg: They had to comment on before noon."),
    PracticeItem(404, PracticeKind.PHRASAL_VERB, "compete with", "try to win against", "Eg: They had to compete with before noon."),
    PracticeItem(405, PracticeKind.PHRASAL_VERB, "complain of", "say one suffers from", "Eg: They had to complain of before noon."),
    PracticeItem(406, PracticeKind.PHRASAL_VERB, "comply with", "obey", "Eg: They had to comply with before noon."),
    PracticeItem(407, PracticeKind.PHRASAL_VERB, "concentrate on", "focus on", "Eg: They had to concentrate on before noon."),
    PracticeItem(408, PracticeKind.PHRASAL_VERB, "conform to", "match a standard", "Eg: They had to conform to before noon."),
    PracticeItem(409, PracticeKind.PHRASAL_VERB, "congratulate on", "express praise for", "Eg: They had to congratulate on before noon."),
    PracticeItem(410, PracticeKind.PHRASAL_VERB, "consist of", "be made up of", "Eg: They had to consist of before noon."),
    PracticeItem(411, PracticeKind.PHRASAL_VERB, "contend with", "struggle against", "Eg: They had to contend with before noon."),
    PracticeItem(412, PracticeKind.PHRASAL_VERB, "contribute to", "help cause", "Eg: They had to contribute to before noon."),
    PracticeItem(413, PracticeKind.PHRASAL_VERB, "cope with", "manage successfully", "Eg: They had to cope with before noon."),
    PracticeItem(414, PracticeKind.PHRASAL_VERB, "correspond to", "match", "Eg: They had to correspond to before noon."),
    PracticeItem(415, PracticeKind.PHRASAL_VERB, "count for", "be worth", "Eg: They had to count for before noon."),
    PracticeItem(416, PracticeKind.PHRASAL_VERB, "cover up", "hide wrongdoing", "Eg: They had to cover up before noon."),
    PracticeItem(417, PracticeKind.PHRASAL_VERB, "decide on", "choose", "Eg: They had to decide on before noon."),
    PracticeItem(418, PracticeKind.PHRASAL_VERB, "depend on", "rely on", "Eg: They had to depend on before noon."),
    PracticeItem(419, PracticeKind.PHRASAL_VERB, "devote to", "give entirely to", "Eg: They had to devote to before noon."),
    PracticeItem(420, PracticeKind.PHRASAL_VERB, "differ from", "be unlike", "Eg: They had to differ from before noon."),
    PracticeItem(421, PracticeKind.PHRASAL_VERB, "dream of", "imagine; aspire to", "Eg: They had to dream of before noon."),
    PracticeItem(422, PracticeKind.PHRASAL_VERB, "dwell on", "think too long about", "Eg: They had to dwell on before noon."),
    PracticeItem(423, PracticeKind.PHRASAL_VERB, "emerge from", "come out of", "Eg: They had to emerge from before noon."),
    PracticeItem(424, PracticeKind.PHRASAL_VERB, "engage in", "take part in", "Eg: They had to engage in before noon."),
    PracticeItem(425, PracticeKind.PHRASAL_VERB, "escape from", "get free from", "Eg: They had to escape from before noon."),
    PracticeItem(426, PracticeKind.PHRASAL_VERB, "excel in", "be outstanding at", "Eg: They had to excel in before noon."),
    PracticeItem(427, PracticeKind.PHRASAL_VERB, "exclude from", "keep out of", "Eg: They had to exclude from before noon."),
    PracticeItem(428, PracticeKind.PHRASAL_VERB, "excuse for", "forgive for", "Eg: They had to excuse for before noon."),
    PracticeItem(429, PracticeKind.PHRASAL_VERB, "experiment with", "try something new", "Eg: They had to experiment with before noon."),
    PracticeItem(430, PracticeKind.PHRASAL_VERB, "focus on", "concentrate on", "Eg: They had to focus on before noon."),
    PracticeItem(431, PracticeKind.PHRASAL_VERB, "forbid from", "not allow", "Eg: They had to forbid from before noon."),
    PracticeItem(432, PracticeKind.PHRASAL_VERB, "glance at", "look quickly at", "Eg: They had to glance at before noon."),
    PracticeItem(433, PracticeKind.PHRASAL_VERB, "graduate from", "complete studies at", "Eg: They had to graduate from before noon."),
    PracticeItem(434, PracticeKind.PHRASAL_VERB, "guard against", "protect from", "Eg: They had to guard against before noon."),
    PracticeItem(435, PracticeKind.PHRASAL_VERB, "hear of", "learn about", "Eg: They had to hear of before noon."),
    PracticeItem(436, PracticeKind.PHRASAL_VERB, "hide from", "keep out of sight of", "Eg: They had to hide from before noon."),
    PracticeItem(437, PracticeKind.PHRASAL_VERB, "hope for", "want and expect", "Eg: They had to hope for before noon."),
    PracticeItem(438, PracticeKind.PHRASAL_VERB, "insist on", "demand firmly", "Eg: They had to insist on before noon."),
    PracticeItem(439, PracticeKind.PHRASAL_VERB, "interfere with", "get in the way of", "Eg: They had to interfere with before noon."),
    PracticeItem(440, PracticeKind.PHRASAL_VERB, "invest in", "put money into", "Eg: They had to invest in before noon."),
    PracticeItem(441, PracticeKind.PHRASAL_VERB, "joke about", "speak humorously about", "Eg: They had to joke about before noon."),
    PracticeItem(442, PracticeKind.PHRASAL_VERB, "know of", "be aware of", "Eg: They had to know of before noon."),
    PracticeItem(443, PracticeKind.PHRASAL_VERB, "laugh at", "mock", "Eg: They had to laugh at before noon."),
    PracticeItem(444, PracticeKind.PHRASAL_VERB, "listen to", "pay attention to sound", "Eg: They had to listen to before noon."),
    PracticeItem(445, PracticeKind.PHRASAL_VERB, "long for", "desire strongly", "Eg: They had to long for before noon."),
    PracticeItem(446, PracticeKind.PHRASAL_VERB, "object to", "oppose", "Eg: They had to object to before noon."),
    PracticeItem(447, PracticeKind.PHRASAL_VERB, "participate in", "take part in", "Eg: They had to participate in before noon."),
    PracticeItem(448, PracticeKind.PHRASAL_VERB, "persist in", "continue firmly", "Eg: They had to persist in before noon."),
    PracticeItem(449, PracticeKind.PHRASAL_VERB, "pray for", "ask God for", "Eg: They had to pray for before noon."),
    PracticeItem(450, PracticeKind.PHRASAL_VERB, "prevent from", "stop from happening", "Eg: They had to prevent from before noon."),
    PracticeItem(451, PracticeKind.PHRASAL_VERB, "protect from", "keep safe from", "Eg: They had to protect from before noon."),
    PracticeItem(452, PracticeKind.PHRASAL_VERB, "provide for", "supply needs of", "Eg: They had to provide for before noon."),
    PracticeItem(453, PracticeKind.PHRASAL_VERB, "react to", "respond to", "Eg: They had to react to before noon."),
    PracticeItem(454, PracticeKind.PHRASAL_VERB, "recover from", "get better after", "Eg: They had to recover from before noon."),
    PracticeItem(455, PracticeKind.PHRASAL_VERB, "refer to", "mention", "Eg: They had to refer to before noon."),
    PracticeItem(456, PracticeKind.PHRASAL_VERB, "rely on", "depend on", "Eg: They had to rely on before noon."),
    PracticeItem(457, PracticeKind.PHRASAL_VERB, "remind of", "cause to remember", "Eg: They had to remind of before noon."),
    PracticeItem(458, PracticeKind.PHRASAL_VERB, "result in", "cause", "Eg: They had to result in before noon."),
    PracticeItem(459, PracticeKind.PHRASAL_VERB, "retire from", "leave a job permanently", "Eg: They had to retire from before noon."),
    PracticeItem(460, PracticeKind.PHRASAL_VERB, "search for", "look for", "Eg: They had to search for before noon."),
    PracticeItem(461, PracticeKind.PHRASAL_VERB, "specialize in", "focus professionally on", "Eg: They had to specialize in before noon."),
    PracticeItem(462, PracticeKind.PHRASAL_VERB, "stare at", "look fixedly at", "Eg: They had to stare at before noon."),
    PracticeItem(463, PracticeKind.PHRASAL_VERB, "stem from", "originate from", "Eg: They had to stem from before noon."),
    PracticeItem(464, PracticeKind.PHRASAL_VERB, "succeed in", "achieve success in", "Eg: They had to succeed in before noon."),
    PracticeItem(465, PracticeKind.PHRASAL_VERB, "suffer from", "be afflicted by", "Eg: They had to suffer from before noon."),
    PracticeItem(466, PracticeKind.PHRASAL_VERB, "suspect of", "believe guilty of", "Eg: They had to suspect of before noon."),
    PracticeItem(467, PracticeKind.PHRASAL_VERB, "think about", "consider", "Eg: They had to think about before noon."),
    PracticeItem(468, PracticeKind.PHRASAL_VERB, "vote for", "choose in an election", "Eg: They had to vote for before noon."),
    PracticeItem(469, PracticeKind.PHRASAL_VERB, "wait for", "stay until something happens", "Eg: They had to wait for before noon."),
    PracticeItem(470, PracticeKind.PHRASAL_VERB, "warn against", "advise not to do", "Eg: They had to warn against before noon."),
    PracticeItem(471, PracticeKind.PHRASAL_VERB, "worry about", "feel anxious about", "Eg: They had to worry about before noon."),
    PracticeItem(472, PracticeKind.ONE_WORD, "A person who loves mankind", "philanthropist", "Answer: philanthropist"),
    PracticeItem(473, PracticeKind.ONE_WORD, "A person who hates mankind", "misanthrope", "Answer: misanthrope"),
    PracticeItem(474, PracticeKind.ONE_WORD, "One who looks at the bright side", "optimist", "Answer: optimist"),
    PracticeItem(475, PracticeKind.ONE_WORD, "One who looks at the dark side", "pessimist", "Answer: pessimist"),
    PracticeItem(476, PracticeKind.ONE_WORD, "A person who can speak two languages", "bilingual", "Answer: bilingual"),
    PracticeItem(477, PracticeKind.ONE_WORD, "A person who can speak many languages", "polyglot", "Answer: polyglot"),
    PracticeItem(478, PracticeKind.ONE_WORD, "One who knows everything", "omniscient", "Answer: omniscient"),
    PracticeItem(479, PracticeKind.ONE_WORD, "One who is present everywhere", "omnipresent", "Answer: omnipresent"),
    PracticeItem(480, PracticeKind.ONE_WORD, "One who is all-powerful", "omnipotent", "Answer: omnipotent"),
    PracticeItem(481, PracticeKind.ONE_WORD, "A person who writes dictionaries", "lexicographer", "Answer: lexicographer"),
    PracticeItem(482, PracticeKind.ONE_WORD, "A person who studies stars", "astronomer", "Answer: astronomer"),
    PracticeItem(483, PracticeKind.ONE_WORD, "A person who studies weather", "meteorologist", "Answer: meteorologist"),
    PracticeItem(484, PracticeKind.ONE_WORD, "A person who mends shoes", "cobbler", "Answer: cobbler"),
    PracticeItem(485, PracticeKind.ONE_WORD, "A person who sells flowers", "florist", "Answer: florist"),
    PracticeItem(486, PracticeKind.ONE_WORD, "A person who sells meat", "butcher", "Answer: butcher"),
    PracticeItem(487, PracticeKind.ONE_WORD, "A person who sells spectacles", "optician", "Answer: optician"),
    PracticeItem(488, PracticeKind.ONE_WORD, "A person who treats teeth", "dentist", "Answer: dentist"),
    PracticeItem(489, PracticeKind.ONE_WORD, "A person who treats eyes", "oculist", "Answer: oculist"),
    PracticeItem(490, PracticeKind.ONE_WORD, "A person who treats animals", "veterinarian", "Answer: veterinarian"),
    PracticeItem(491, PracticeKind.ONE_WORD, "A person who compiles a dictionary", "lexicographer", "Answer: lexicographer"),
    PracticeItem(492, PracticeKind.ONE_WORD, "A government by the people", "democracy", "Answer: democracy"),
    PracticeItem(493, PracticeKind.ONE_WORD, "A government by a king", "monarchy", "Answer: monarchy"),
    PracticeItem(494, PracticeKind.ONE_WORD, "A government by the rich", "plutocracy", "Answer: plutocracy"),
    PracticeItem(495, PracticeKind.ONE_WORD, "A government by the nobles", "aristocracy", "Answer: aristocracy"),
    PracticeItem(496, PracticeKind.ONE_WORD, "A government by officials", "bureaucracy", "Answer: bureaucracy"),
    PracticeItem(497, PracticeKind.ONE_WORD, "Rule by a few", "oligarchy", "Answer: oligarchy"),
    PracticeItem(498, PracticeKind.ONE_WORD, "Absence of government", "anarchy", "Answer: anarchy"),
    PracticeItem(499, PracticeKind.ONE_WORD, "Life story of a person written by another", "biography", "Answer: biography"),
    PracticeItem(500, PracticeKind.ONE_WORD, "Life story written by oneself", "autobiography", "Answer: autobiography"),
    PracticeItem(501, PracticeKind.ONE_WORD, "A book published after the author's death", "posthumous", "Answer: posthumous"),
    PracticeItem(502, PracticeKind.ONE_WORD, "Something that lasts forever", "eternal", "Answer: eternal"),
    PracticeItem(503, PracticeKind.ONE_WORD, "That which cannot be read", "illegible", "Answer: illegible"),
    PracticeItem(504, PracticeKind.ONE_WORD, "That which cannot be heard", "inaudible", "Answer: inaudible"),
    PracticeItem(505, PracticeKind.ONE_WORD, "That which cannot be seen", "invisible", "Answer: invisible"),
    PracticeItem(506, PracticeKind.ONE_WORD, "That which cannot be conquered", "invincible", "Answer: invincible"),
    PracticeItem(507, PracticeKind.ONE_WORD, "That which cannot be believed", "incredible", "Answer: incredible"),
    PracticeItem(508, PracticeKind.ONE_WORD, "That which cannot be avoided", "inevitable", "Answer: inevitable"),
    PracticeItem(509, PracticeKind.ONE_WORD, "That which cannot be corrected", "incorrigible", "Answer: incorrigible"),
    PracticeItem(510, PracticeKind.ONE_WORD, "That which cannot be repaired", "irreparable", "Answer: irreparable"),
    PracticeItem(511, PracticeKind.ONE_WORD, "That which cannot be imitated", "inimitable", "Answer: inimitable"),
    PracticeItem(512, PracticeKind.ONE_WORD, "That which cannot be practised", "impracticable", "Answer: impracticable"),
    PracticeItem(513, PracticeKind.ONE_WORD, "That which cannot be satisfied", "insatiable", "Answer: insatiable"),
    PracticeItem(514, PracticeKind.ONE_WORD, "A speech made without preparation", "extempore", "Answer: extempore"),
    PracticeItem(515, PracticeKind.ONE_WORD, "A person who walks on foot", "pedestrian", "Answer: pedestrian"),
    PracticeItem(516, PracticeKind.ONE_WORD, "A person who journeys to a sacred place", "pilgrim", "Answer: pilgrim"),
    PracticeItem(517, PracticeKind.ONE_WORD, "A person who lives alone", "recluse", "Answer: recluse"),
    PracticeItem(518, PracticeKind.ONE_WORD, "A person who spends too much", "spendthrift", "Answer: spendthrift"),
    PracticeItem(519, PracticeKind.ONE_WORD, "A person who saves money", "miser", "Answer: miser"),
    PracticeItem(520, PracticeKind.ONE_WORD, "One who is new to a profession", "novice", "Answer: novice"),
    PracticeItem(521, PracticeKind.ONE_WORD, "One who is skilled in many fields", "versatile", "Answer: versatile"),
    PracticeItem(522, PracticeKind.ONE_WORD, "One who eats human flesh", "cannibal", "Answer: cannibal"),
    PracticeItem(523, PracticeKind.ONE_WORD, "One who collects stamps", "philatelist", "Answer: philatelist"),
    PracticeItem(524, PracticeKind.ONE_WORD, "One who collects coins", "numismatist", "Answer: numismatist"),
    PracticeItem(525, PracticeKind.ONE_WORD, "One who loves books", "bibliophile", "Answer: bibliophile"),
    PracticeItem(526, PracticeKind.ONE_WORD, "A place where birds are kept", "aviary", "Answer: aviary"),
    PracticeItem(527, PracticeKind.ONE_WORD, "A place where bees are kept", "apiary", "Answer: apiary"),
    PracticeItem(528, PracticeKind.ONE_WORD, "A place where animals are kept", "zoo", "Answer: zoo"),
    PracticeItem(529, PracticeKind.ONE_WORD, "A place for storing grain", "granary", "Answer: granary"),
    PracticeItem(530, PracticeKind.ONE_WORD, "A place where clothes are washed", "laundry", "Answer: laundry"),
    PracticeItem(531, PracticeKind.ONE_WORD, "A place where dead bodies are kept", "mortuary", "Answer: mortuary"),
    PracticeItem(532, PracticeKind.ONE_WORD, "A place where weapons are stored", "arsenal", "Answer: arsenal"),
    PracticeItem(533, PracticeKind.ONE_WORD, "A place for public worship", "temple", "Answer: temple"),
    PracticeItem(534, PracticeKind.ONE_WORD, "A building where soldiers live", "barracks", "Answer: barracks"),
    PracticeItem(535, PracticeKind.ONE_WORD, "A room for clothes", "wardrobe", "Answer: wardrobe"),
    PracticeItem(536, PracticeKind.ONE_WORD, "A list of books", "catalogue", "Answer: catalogue"),
    PracticeItem(537, PracticeKind.ONE_WORD, "A list of dishes", "menu", "Answer: menu"),
    PracticeItem(538, PracticeKind.ONE_WORD, "A short stay at a place", "sojourn", "Answer: sojourn"),
    PracticeItem(539, PracticeKind.ONE_WORD, "A sudden rush of wind", "gust", "Answer: gust"),
    PracticeItem(540, PracticeKind.ONE_WORD, "A heavy continuous rain", "downpour", "Answer: downpour"),
    PracticeItem(541, PracticeKind.ONE_WORD, "A period of ten years", "decade", "Answer: decade"),
    PracticeItem(542, PracticeKind.ONE_WORD, "A period of hundred years", "century", "Answer: century"),
    PracticeItem(543, PracticeKind.ONE_WORD, "A period of thousand years", "millennium", "Answer: millennium"),
    PracticeItem(544, PracticeKind.ONE_WORD, "Occurring once a year", "annual", "Answer: annual"),
    PracticeItem(545, PracticeKind.ONE_WORD, "Occurring twice a year", "biannual", "Answer: biannual"),
    PracticeItem(546, PracticeKind.ONE_WORD, "Occurring every two years", "biennial", "Answer: biennial"),
    PracticeItem(547, PracticeKind.ONE_WORD, "Belonging to all parts of the world", "universal", "Answer: universal"),
    PracticeItem(548, PracticeKind.ONE_WORD, "Belonging to the Middle Ages", "medieval", "Answer: medieval"),
    PracticeItem(549, PracticeKind.ONE_WORD, "Existing only in name", "nominal", "Answer: nominal"),
    PracticeItem(550, PracticeKind.ONE_WORD, "Done according to custom", "customary", "Answer: customary"),
    PracticeItem(551, PracticeKind.ONE_WORD, "Capable of being seen through", "transparent", "Answer: transparent"),
    PracticeItem(552, PracticeKind.ONE_WORD, "Not allowing light to pass", "opaque", "Answer: opaque"),
    PracticeItem(553, PracticeKind.ONE_WORD, "Easily broken", "fragile", "Answer: fragile"),
    PracticeItem(554, PracticeKind.ONE_WORD, "Lasting for a short time", "temporary", "Answer: temporary"),
    PracticeItem(555, PracticeKind.ONE_WORD, "Lasting for a long time", "permanent", "Answer: permanent"),
    PracticeItem(556, PracticeKind.ONE_WORD, "Open to all", "public", "Answer: public"),
    PracticeItem(557, PracticeKind.ONE_WORD, "Belonging to an individual", "private", "Answer: private"),
    PracticeItem(558, PracticeKind.ONE_WORD, "One who deserts religion", "apostate", "Answer: apostate"),
    PracticeItem(559, PracticeKind.ONE_WORD, "One who believes in fate", "fatalist", "Answer: fatalist"),
    PracticeItem(560, PracticeKind.ONE_WORD, "One who questions everything", "sceptic", "Answer: sceptic"),
    PracticeItem(561, PracticeKind.ONE_WORD, "One who does not believe in God", "atheist", "Answer: atheist"),
    PracticeItem(562, PracticeKind.ONE_WORD, "One who believes in God", "theist", "Answer: theist"),
    PracticeItem(563, PracticeKind.ONE_WORD, "One who loves his country", "patriot", "Answer: patriot"),
    PracticeItem(564, PracticeKind.ONE_WORD, "One who betrays his country", "traitor", "Answer: traitor"),
    PracticeItem(565, PracticeKind.ONE_WORD, "Fear of heights", "acrophobia", "Answer: acrophobia"),
    PracticeItem(566, PracticeKind.ONE_WORD, "Fear of water", "hydrophobia", "Answer: hydrophobia"),
    PracticeItem(567, PracticeKind.ONE_WORD, "Fear of closed spaces", "claustrophobia", "Answer: claustrophobia"),
    PracticeItem(568, PracticeKind.ONE_WORD, "Fear of strangers", "xenophobia", "Answer: xenophobia"),
    PracticeItem(569, PracticeKind.ONE_WORD, "Study of plants", "botany", "Answer: botany"),
    PracticeItem(570, PracticeKind.ONE_WORD, "Study of animals", "zoology", "Answer: zoology"),
    PracticeItem(571, PracticeKind.ONE_WORD, "Study of human societies", "sociology", "Answer: sociology"),
    PracticeItem(572, PracticeKind.ONE_WORD, "Study of the mind", "psychology", "Answer: psychology"),
    PracticeItem(573, PracticeKind.ONE_WORD, "Study of coins", "numismatics", "Answer: numismatics"),
    PracticeItem(574, PracticeKind.ONE_WORD, "Study of handwriting", "graphology", "Answer: graphology"),
    PracticeItem(575, PracticeKind.ONE_WORD, "Killing of a human being", "homicide", "Answer: homicide"),
    PracticeItem(576, PracticeKind.ONE_WORD, "Killing of one's father", "patricide", "Answer: patricide"),
    PracticeItem(577, PracticeKind.ONE_WORD, "Killing of one's mother", "matricide", "Answer: matricide"),
    PracticeItem(578, PracticeKind.ONE_WORD, "Killing of a king", "regicide", "Answer: regicide"),
    PracticeItem(579, PracticeKind.ONE_WORD, "Killing of an infant", "infanticide", "Answer: infanticide"),
    PracticeItem(580, PracticeKind.ONE_WORD, "Killing of a race", "genocide", "Answer: genocide"),
    PracticeItem(581, PracticeKind.ONE_WORD, "A person who cannot pay debts", "insolvent", "Answer: insolvent"),
    PracticeItem(582, PracticeKind.ONE_WORD, "A person with a long experience", "veteran", "Answer: veteran"),
    PracticeItem(583, PracticeKind.ONE_WORD, "A person who travels to work daily", "commuter", "Answer: commuter"),
    PracticeItem(584, PracticeKind.ONE_WORD, "A person who leaves his country", "emigrant", "Answer: emigrant"),
    PracticeItem(585, PracticeKind.ONE_WORD, "A person who comes into a country", "immigrant", "Answer: immigrant"),
    PracticeItem(586, PracticeKind.ONE_WORD, "Words inscribed on a tomb", "epitaph", "Answer: epitaph"),
    PracticeItem(587, PracticeKind.ONE_WORD, "A signature of a celebrity", "autograph", "Answer: autograph"),
    PracticeItem(588, PracticeKind.ONE_WORD, "A handwritten document", "manuscript", "Answer: manuscript"),
    PracticeItem(589, PracticeKind.ONE_WORD, "A notice of someone's death", "obituary", "Answer: obituary"),
    PracticeItem(590, PracticeKind.ONE_WORD, "A formal expression of praise", "eulogy", "Answer: eulogy"),
    PracticeItem(591, PracticeKind.ONE_WORD, "A speech of praise", "panegyric", "Answer: panegyric"),
    PracticeItem(592, PracticeKind.ONE_WORD, "A humorous imitation", "parody", "Answer: parody"),
    PracticeItem(593, PracticeKind.ONE_WORD, "A story with a moral", "fable", "Answer: fable"),
    PracticeItem(594, PracticeKind.ONE_WORD, "A short poem with fourteen lines", "sonnet", "Answer: sonnet"),
    PracticeItem(595, PracticeKind.ONE_WORD, "A poem of mourning", "elegy", "Answer: elegy"),
    PracticeItem(596, PracticeKind.ONE_WORD, "A song of praise to God", "hymn", "Answer: hymn"),
    PracticeItem(597, PracticeKind.ONE_WORD, "A false name used by a writer", "pseudonym", "Answer: pseudonym"),
    PracticeItem(598, PracticeKind.ONE_WORD, "Something no longer in use", "obsolete", "Answer: obsolete"),
    PracticeItem(599, PracticeKind.ONE_WORD, "Something existing from birth", "congenital", "Answer: congenital"),
    PracticeItem(600, PracticeKind.ONE_WORD, "Medicine that softens the bowels", "laxative", "Answer: laxative"),
    PracticeItem(601, PracticeKind.ONE_WORD, "Medicine that induces sleep", "sedative", "Answer: sedative"),
    PracticeItem(602, PracticeKind.ONE_WORD, "Medicine that kills germs", "antiseptic", "Answer: antiseptic"),
    PracticeItem(603, PracticeKind.ONE_WORD, "A cure for all diseases", "panacea", "Answer: panacea"),
    PracticeItem(604, PracticeKind.ONE_WORD, "A substance that causes death", "poison", "Answer: poison"),
    PracticeItem(605, PracticeKind.ONE_WORD, "An exact copy", "facsimile", "Answer: facsimile"),
    PracticeItem(606, PracticeKind.ONE_WORD, "A person who introduces speakers", "compere", "Answer: compere"),
    PracticeItem(607, PracticeKind.ONE_WORD, "A person who designs buildings", "architect", "Answer: architect"),
    PracticeItem(608, PracticeKind.ONE_WORD, "A person who draws maps", "cartographer", "Answer: cartographer"),
    PracticeItem(609, PracticeKind.ONE_WORD, "A person who makes pottery", "potter", "Answer: potter"),
    PracticeItem(610, PracticeKind.ONE_WORD, "A person who cuts hair", "barber", "Answer: barber"),
    PracticeItem(611, PracticeKind.ONE_WORD, "A person who mends water pipes", "plumber", "Answer: plumber"),
    PracticeItem(612, PracticeKind.ONE_WORD, "A person who drives a car for pay", "chauffeur", "Answer: chauffeur"),
    PracticeItem(613, PracticeKind.ONE_WORD, "A person who rides horses in races", "jockey", "Answer: jockey"),
    PracticeItem(614, PracticeKind.ONE_WORD, "A group of sheep", "flock", "Answer: flock"),
    PracticeItem(615, PracticeKind.ONE_WORD, "A group of cattle", "herd", "Answer: herd"),
    PracticeItem(616, PracticeKind.ONE_WORD, "A group of wolves", "pack", "Answer: pack"),
    PracticeItem(617, PracticeKind.ONE_WORD, "A group of bees", "swarm", "Answer: swarm"),
    PracticeItem(618, PracticeKind.ONE_WORD, "A group of lions", "pride", "Answer: pride"),
    PracticeItem(619, PracticeKind.ONE_WORD, "A group of fish", "shoal", "Answer: shoal"),
    PracticeItem(620, PracticeKind.ONE_WORD, "A group of islands", "archipelago", "Answer: archipelago"),
    PracticeItem(621, PracticeKind.ONE_WORD, "A group of stars", "constellation", "Answer: constellation"),
    PracticeItem(622, PracticeKind.ONE_WORD, "A place where money is coined", "mint", "Answer: mint"),
    PracticeItem(623, PracticeKind.ONE_WORD, "A place where ships are repaired", "dockyard", "Answer: dockyard"),
    PracticeItem(624, PracticeKind.ONE_WORD, "A place where films are shown", "cinema", "Answer: cinema"),
    PracticeItem(625, PracticeKind.ONE_WORD, "A place where experiments are done", "laboratory", "Answer: laboratory"),
    PracticeItem(626, PracticeKind.ONE_WORD, "A place where historical objects are kept", "museum", "Answer: museum"),
    PracticeItem(627, PracticeKind.ONE_WORD, "A place for keeping aeroplanes", "hangar", "Answer: hangar"),
    PracticeItem(628, PracticeKind.ONE_WORD, "One who is easily deceived", "gullible", "Answer: gullible"),
    PracticeItem(629, PracticeKind.ONE_WORD, "One who is hard to please", "fastidious", "Answer: fastidious"),
    PracticeItem(630, PracticeKind.ONE_WORD, "One who speaks less", "reticent", "Answer: reticent"),
    PracticeItem(631, PracticeKind.ONE_WORD, "One who talks too much", "loquacious", "Answer: loquacious"),
    PracticeItem(632, PracticeKind.ONE_WORD, "One who is present at an event", "spectator", "Answer: spectator"),
    PracticeItem(633, PracticeKind.ONE_WORD, "One who listens secretly", "eavesdropper", "Answer: eavesdropper"),
    PracticeItem(634, PracticeKind.ONE_WORD, "One who walks in sleep", "somnambulist", "Answer: somnambulist"),
    PracticeItem(635, PracticeKind.ONE_WORD, "One who talks in sleep", "somniloquist", "Answer: somniloquist"),
    PracticeItem(636, PracticeKind.ONE_WORD, "One who copies from others", "plagiarist", "Answer: plagiarist"),
    PracticeItem(637, PracticeKind.ONE_WORD, "One who is indifferent to pain", "stoic", "Answer: stoic"),
    PracticeItem(638, PracticeKind.ONE_WORD, "One who is beyond reform", "incorrigible", "Answer: incorrigible"),
    PracticeItem(639, PracticeKind.ONE_WORD, "One who is greedy for money", "avaricious", "Answer: avaricious"),
    PracticeItem(640, PracticeKind.ONE_WORD, "One who is without manners", "uncouth", "Answer: uncouth"),
    PracticeItem(641, PracticeKind.ONE_WORD, "A decision that cannot be changed", "irrevocable", "Answer: irrevocable"),
    PracticeItem(642, PracticeKind.ONE_WORD, "A loss that cannot be repaired", "irreparable", "Answer: irreparable"),
    PracticeItem(643, PracticeKind.ONE_WORD, "A person who is blind to one eye", "monocular", "Answer: monocular"),
    PracticeItem(644, PracticeKind.ONE_WORD, "Capable of catching fire easily", "inflammable", "Answer: inflammable"),
    PracticeItem(645, PracticeKind.ONE_WORD, "Not based on facts", "fictitious", "Answer: fictitious"),
    PracticeItem(646, PracticeKind.ONE_WORD, "Belonging to the same period", "contemporary", "Answer: contemporary"),
    PracticeItem(647, PracticeKind.ONE_WORD, "Existing at the same time", "simultaneous", "Answer: simultaneous"),
    PracticeItem(648, PracticeKind.ONE_WORD, "Happening every night", "nocturnal", "Answer: nocturnal"),
    PracticeItem(649, PracticeKind.ONE_WORD, "Active during day", "diurnal", "Answer: diurnal"),
    PracticeItem(650, PracticeKind.ONE_WORD, "A person of odd habits", "eccentric", "Answer: eccentric"),
    PracticeItem(651, PracticeKind.ONE_WORD, "A sudden and violent change", "cataclysm", "Answer: cataclysm"),
    PracticeItem(652, PracticeKind.ONE_WORD, "A speech delivered for the first time", "maiden", "Answer: maiden"),
    PracticeItem(653, PracticeKind.ONE_WORD, "A person who has no money", "pauper", "Answer: pauper"),
    PracticeItem(654, PracticeKind.ONE_WORD, "A person who is very rich", "affluent", "Answer: affluent"),
    PracticeItem(655, PracticeKind.ONE_WORD, "To give up the throne", "abdicate", "Answer: abdicate"),
    PracticeItem(656, PracticeKind.ONE_WORD, "To go from bad to worse", "deteriorate", "Answer: deteriorate"),
    PracticeItem(657, PracticeKind.ONE_WORD, "To increase the speed", "accelerate", "Answer: accelerate"),
    PracticeItem(658, PracticeKind.ONE_WORD, "To decrease the speed", "retard", "Answer: retard"),
    PracticeItem(659, PracticeKind.ONE_WORD, "To make something less severe", "mitigate", "Answer: mitigate"),
    PracticeItem(660, PracticeKind.ONE_WORD, "To make something more severe", "aggravate", "Answer: aggravate"),
    PracticeItem(661, PracticeKind.ONE_WORD, "To express strong disapproval", "censure", "Answer: censure"),
    PracticeItem(662, PracticeKind.ONE_WORD, "To free from blame", "exonerate", "Answer: exonerate"),
    PracticeItem(663, PracticeKind.ONE_WORD, "To cancel a marriage", "annul", "Answer: annul"),
    PracticeItem(664, PracticeKind.ONE_WORD, "To give a false appearance", "camouflage", "Answer: camouflage"),
    )
}
